services:
  - type: web
    name: schedule-a-poll
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    disk:
      name: poll-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
